-- Grant anon/authenticated access to profile language columns needed by public profile pages
alter table public.profiles add column if not exists lang_switcher_enabled boolean not null default false;
alter table public.profiles add column if not exists enabled_languages jsonb;
alter table public.profiles add column if not exists default_lang text not null default 'az';

grant select (
  id,
  slug,
  enabled,
  name,
  profession,
  bio,
  phone,
  phone2,
  whatsapp,
  whatsapp2,
  instagram,
  tiktok,
  telegram,
  threads,
  waze,
  website,
  facebook,
  x,
  linkedin,
  youtube,
  behance,
  location,
  location_url,
  google_review_url,
  email,
  avatar_url,
  background_url,
  cover_style,
  cover_position,
  avatar_shape,
  gallery,
  catalog,
  theme,
  created_at,
  updated_at,
  cv_url,
  reservation_enabled,
  portfolio_enabled,
  referral_enabled,
  referral_url,
  views_count,
  saves_count,
  stats_enabled,
  lang_switcher_enabled,
  enabled_languages,
  default_lang
) on table public.profiles to anon, authenticated;
